Uuencode (#70)
* remove uuencode in favor of pack()

* change from Text::Fuzzy to Text::Levenshtein

* unit test installs perl-text-levenshtein

* force cache

* bring back rest of CI

* debug messages

* bash -x filterTaxonomy

* force cache with taxonkit

* restore full test

* remove bash -x for filterTaxonomy

* tree debugging statement

* don't make very simple kraken database

* skip over ls kraken database

* bump version

diff --git a/.github/workflows/unittests.yml b/.github/workflows/unittests.yml
--- a/.github/workflows/unittests.yml
+++ b/.github/workflows/unittests.yml
@@ -59,7 +59,7 @@ jobs:
             #/usr/share/miniconda
           key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-perl_v${{ matrix.perl }}--${{env.CACHE_NUMBER}}
         env:
-          CACHE_NUMBER: 7
+          CACHE_NUMBER: 1
       - name: conda installations
         shell: bash -el {0}
         if: steps.cache-conda.outputs.cache-hit != 'true'
@@ -68,8 +68,8 @@ jobs:
             kmc lighter megahit pilon trimmomatic perl-bioperl kraken=1 \
             spades skesa=2.4 python=3.7 perl-cg-pipeline perl-gd blast prodigal \
             perl-app-cpanminus perl-statistics-descriptive perl-config-simple \
-            perl-file-slurp perl-moo perl-list-moreutils kma=1.4 \
-            multiqc fastqc bowtie2 perl-gd perl-gdgraph salmid staramr kalamari
+            perl-file-slurp perl-text-levenshtein perl-moo perl-list-moreutils kma=1.4 \
+            multiqc fastqc bowtie2 perl-gd perl-gdgraph salmid staramr kalamari taxonkit
       - name: check installation
         shell: bash -el {0}
         run: | 
@@ -118,13 +118,19 @@ jobs:
         env:
           CACHE_NUMBER: 0
       - name: make very simple kraken database
-        if: steps.cache-kraken.outputs.cache-hit != 'true'
+        if: false
+        #if: steps.cache-kraken.outputs.cache-hit != 'true'
         shell: bash -el {0}
         run: |
           which downloadKalamari.sh
           KALAMARI_DEBUG=1 downloadKalamari.sh
+          echo "Running buildTaxonomy.sh"
           buildTaxonomy.sh
-          filterTaxonomy.sh
+          echo
+          tree $(dirname $(which downloadKalamari.sh))/../share/kalamari-*
+          echo
+          echo "Running filterTaxonomy.sh"
+          bash -x filterTaxonomy.sh
           echo
           tree $(dirname $(which downloadKalamari.sh))/../share/kalamari-*
           echo
@@ -190,7 +196,7 @@ jobs:
           kalamari_ver=$(downloadKalamari.pl --version)
           kraken_dir="$condabin/../share/kalamari-$kalamari_ver/kalamari-kraken"
           echo $kraken_dir
-          ls -lh $kraken_dir
+          ls -lh $kraken_dir || echo "ERROR: could not ls $kraken_dir"
           echo "KRAKEN_DEFAULT_DB  $kraken_dir" >> config/settings.conf
           make
           make test
